"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import StoreHeader from "../../components/StoreHeader";
import { API_URL } from "../../lib/store";

export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch(`${API_URL}/api/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Não foi possível entrar."); localStorage.setItem("paty_token", result.token); localStorage.setItem("paty_user", JSON.stringify(result.user)); router.push(result.user.role === "ADMIN" ? "/admin" : "/conta"); } catch (error) { setError(error instanceof TypeError ? "Não foi possível conectar ao servidor. Verifique se a API está ligada na porta 4000." : error instanceof Error ? error.message : "Não foi possível entrar."); } finally { setLoading(false); } }
  return <div className="min-h-screen bg-[#f7f4f0]"><StoreHeader /><main className="mx-auto max-w-md px-4 py-14"><div className="rounded-[28px] border border-[#eadbb1] bg-white p-7 shadow-sm sm:p-10"><img src="/logo-paty-flores.svg" alt="Paty Flores" className="mx-auto h-24 w-24 object-contain" /><h1 className="mt-5 text-center text-3xl font-semibold">Entrar na sua conta</h1><p className="mt-2 text-center text-sm text-[#6a5555]">Acompanhe pedidos e compre com mais facilidade.</p>{error && <p className="mt-5 rounded-xl bg-[#f9e1dc] px-4 py-3 text-sm text-[#8b3830]">{error}</p>}<form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-semibold">E-mail<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-2xl border border-[#eadbb1] px-4 py-3 outline-none focus:border-[#c69d2f]" /></label><label className="block text-sm font-semibold">Senha<input required minLength={6} type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-2xl border border-[#eadbb1] px-4 py-3 outline-none focus:border-[#c69d2f]" /></label><button disabled={loading} className="w-full rounded-2xl bg-[#2d1d1e] px-5 py-3.5 font-bold text-white disabled:opacity-60">{loading ? "Entrando..." : "Entrar"}</button></form><p className="mt-6 text-center text-sm text-[#6a5555]">Ainda não tem conta? <Link href="/cadastro" className="font-bold text-[#8d6f1d]">Cadastre-se</Link></p></div></main></div>;
}
