"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import StoreHeader from "../../../components/StoreHeader";
import { API_URL, price } from "../../../lib/store";

const steps = [{ key: "PENDING", label: "Pedido recebido" }, { key: "CONFIRMED", label: "Pagamento confirmado" }, { key: "PREPARING", label: "Em preparo" }, { key: "OUT_FOR_DELIVERY", label: "Saiu para entrega" }, { key: "DELIVERED", label: "Entregue" }];
export default function OrderPage({ params }: { params: Promise<{ id: string }> }) { const [order, setOrder] = useState<any>(null); const [loading, setLoading] = useState(true); useEffect(() => { params.then(({ id }) => { const token = localStorage.getItem("paty_token"); fetch(`${API_URL}/api/orders/${id}`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }).then((response) => response.ok ? response.json() : null).then(setOrder).finally(() => setLoading(false)); }); }, [params]); if (loading) return <div className="min-h-screen bg-[#f7f4f0]"><StoreHeader /><main className="p-20 text-center">Carregando pedido...</main></div>; if (!order) return <div className="min-h-screen bg-[#f7f4f0]"><StoreHeader /><main className="p-20 text-center"><h1 className="text-2xl font-semibold">Pedido não encontrado</h1><Link href="/conta" className="mt-4 inline-block font-bold text-[#8d6f1d]">Voltar para minha conta</Link></main></div>; const current = steps.findIndex((step) => step.key === order.status); return <div className="min-h-screen bg-[#f7f4f0] text-[#2d1d1e]"><StoreHeader /><main className="mx-auto max-w-3xl px-4 py-12 md:px-8"><div className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#f5e7aa] text-2xl">✓</div><p className="mt-5 text-xs font-bold uppercase tracking-[0.25em] text-[#8d6f1d]">Pedido confirmado</p><h1 className="mt-2 text-4xl font-semibold">Obrigado pela sua compra</h1><p className="mt-3 text-[#6a5555]">Pedido #{order.id.slice(-8)}</p></div><section className="mt-10 rounded-[24px] border border-[#eadbb1] bg-white p-6"><div className="grid gap-5 sm:grid-cols-5">{steps.map((step, index) => <div key={step.key} className="text-center"><div className={`mx-auto flex h-9 w-9 items-center justify-center rounded-full text-sm font-bold ${index <= current ? "bg-[#e0b63b] text-[#2d1d1e]" : "bg-[#eee8e0] text-[#8b7b7b]"}`}>{index + 1}</div><p className="mt-2 text-xs font-semibold text-[#6a5555]">{step.label}</p></div>)}</div></section><section className="mt-6 rounded-[24px] border border-[#eadbb1] bg-white p-6"><h2 className="text-xl font-semibold">Resumo</h2><div className="mt-5 space-y-3">{order.items.map((item: any) => <div key={item.id} className="flex justify-between text-sm"><span>{item.quantity}x {item.name}</span><span>{price(Number(item.price) * item.quantity)}</span></div>)}</div><div className="mt-5 flex justify-between border-t border-[#eadbb1] pt-4 font-bold"><span>Total</span><span>{price(order.total)}</span></div><p className="mt-5 text-sm text-[#6a5555]">Entrega em: {order.address}, {order.addressNumber}, {order.neighborhood} - {order.city}</p></section><div className="mt-6 text-center"><Link href="/produtos" className="rounded-full bg-[#2d1d1e] px-6 py-3 text-sm font-bold text-white">Continuar comprando</Link></div></main></div>; }
