"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import StoreHeader from "../../components/StoreHeader";
import { cartSubtotal, getCart, price, saveCart, type CartItem } from "../../lib/store";

export default function CartPage() {
  const [items, setItems] = useState<CartItem[]>([]);
  useEffect(() => setItems(getCart()), []);
  const update = (next: CartItem[]) => { setItems(next); saveCart(next); };
  const subtotal = cartSubtotal(items); const delivery = subtotal >= 149 || subtotal === 0 ? 0 : 18.9;
  return <div className="min-h-screen bg-[#f7f4f0] text-[#2d1d1e]"><StoreHeader /><main className="mx-auto max-w-5xl px-4 py-10 md:px-8"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#8d6f1d]">Seu pedido</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.05em]">Carrinho</h1>{items.length === 0 ? <div className="mt-8 rounded-[28px] border border-[#eadbb1] bg-white p-10 text-center"><h2 className="text-2xl font-semibold">Seu carrinho está esperando flores</h2><p className="mt-3 text-[#6a5555]">Escolha algo especial para começar.</p><Link href="/produtos" className="mt-6 inline-block rounded-full bg-[#e0b63b] px-6 py-3 text-sm font-bold">Explorar produtos</Link></div> : <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_340px]"><section className="space-y-3">{items.map((item) => <div key={item.id} className="flex gap-4 rounded-2xl border border-[#eadbb1] bg-white p-4"><div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-xl bg-[#fff8e5] p-3"><img src={item.imageUrl || "/logo-paty-flores.svg"} alt="" className="max-h-full max-w-full object-contain" /></div><div className="min-w-0 flex-1"><Link href={`/produtos/${item.id}`} className="font-semibold hover:text-[#a47a16]">{item.name}</Link><p className="mt-1 text-sm text-[#6a5555]">{price(item.price)}</p><div className="mt-3 flex items-center gap-2"><button onClick={() => update(items.map((current) => current.id === item.id ? { ...current, quantity: Math.max(1, current.quantity - 1) } : current))} className="h-8 w-8 rounded-lg border">−</button><span className="w-6 text-center text-sm font-bold">{item.quantity}</span><button onClick={() => update(items.map((current) => current.id === item.id ? { ...current, quantity: Math.min(current.stock, current.quantity + 1) } : current))} className="h-8 w-8 rounded-lg border">+</button><button onClick={() => update(items.filter((current) => current.id !== item.id))} className="ml-3 text-xs font-bold text-[#a04a43]">Remover</button></div></div><strong>{price(Number(item.price) * item.quantity)}</strong></div>)}</section><aside className="h-fit rounded-[24px] bg-[#2d1d1e] p-6 text-white"><h2 className="text-xl font-semibold">Resumo</h2><div className="mt-6 space-y-3 text-sm text-[#eadfdb]"><div className="flex justify-between"><span>Subtotal</span><span>{price(subtotal)}</span></div><div className="flex justify-between"><span>Entrega</span><span>{delivery === 0 ? "Grátis" : price(delivery)}</span></div></div><div className="mt-5 flex justify-between border-t border-[#594143] pt-5 text-lg font-bold"><span>Total</span><span>{price(subtotal + delivery)}</span></div><Link href="/checkout" className="mt-6 block rounded-2xl bg-[#f3d77d] px-5 py-3 text-center text-sm font-bold text-[#2d1d1e]">Continuar para entrega</Link><Link href="/produtos" className="mt-4 block text-center text-xs text-[#eadfdb]">Continuar comprando</Link></aside></div>}</main></div>;
}
